// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/account"
    | "/api/bulletin/sweep"
    | "/api/policies"
    | `/api/runs/${string}/decide`
    | `/api/runs/${string}/findings`
    | "/api/runs/scan"
    | "/bulletin-admin"
    | `/bulletin/${string}`
    | "/connect"
    | "/connect/return"
    | "/events"
    | "/fleet"
    | "/health"
    | "/hooks/forgejo"
    | "/hooks/github"
    | "/hooks/linear"
    | "/hooks/observe"
    | "/hooks/slack"
    | "/knowledge"
    | "/login"
    | "/logout"
    | "/oidc/callback"
    | "/oidc/login"
    | "/policies"
    | "/projects"
    | "/reviews"
    | "/runs"
    | `/runs/${string}`
    | "/settings"
    | "/sources"
    | "/spend"
  }
}

export {};
