// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/hooks/forgejo"
    | "/login"
    | `/runs/${string}`
  }
}

export {};
