// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/account"
    | `/api/runs/${string}/decide`
    | "/events"
    | "/fleet"
    | "/health"
    | "/hooks/forgejo"
    | "/hooks/github"
    | "/hooks/linear"
    | "/hooks/slack"
    | "/knowledge"
    | "/login"
    | "/oidc/callback"
    | "/oidc/login"
    | "/reviews"
    | "/runs"
    | `/runs/${string}`
    | "/settings"
    | "/sources"
    | "/spend"
  }
}

export {};
