import test from "node:test";
import assert from "node:assert/strict";
import { VERIFICATION_END, VERIFICATION_START, spliceVerification, verificationSection } from "./verification.js";
import type { PreviewOutcome } from "./deploy.js";
import type { TelemetryVerdict } from "./observe.js";

const DEPLOYED: PreviewOutcome = { kind: "deployed", url: "https://preview-fix.example.com", image: "api-build-abc1234" };
const COMPARED: TelemetryVerdict = {
  kind: "compared",
  before: { service: "api", requests: 1000, errors: 50, errorRate: 0.05, p50: 40, p95: 200, p99: 400, apdex: 0.9 },
  after: { service: "api", requests: 900, errors: 9, errorRate: 0.01, p50: 35, p95: 150, p99: 300, apdex: 0.95 },
  errorRateDelta: -0.04,
  p95Delta: -50,
};

test("the section carries the URL and the numbers together", () => {
  const section = verificationSection({ preview: DEPLOYED, telemetry: COMPARED }, "run-1");
  assert.ok(section !== null);
  assert.match(section!, /## Verification/);
  assert.match(section!, /https:\/\/preview-fix\.example\.com/);
  assert.match(section!, /5\.00%/);
  assert.match(section!, /1\.00%/);
  assert.ok(section!.startsWith(VERIFICATION_START) && section!.endsWith(VERIFICATION_END));
});

test("a worker wired for neither feature adds nothing at all", () => {
  // Printing "not deployed, not measured" on every PR trains a reviewer to
  // skip the section that sometimes carries the real thing.
  assert.equal(verificationSection({}, "run-1"), null);
  assert.equal(verificationSection({ preview: { kind: "skipped", reason: "no preview target" } }, "run-1"), null);
  assert.equal(verificationSection({ telemetry: { kind: "disabled", reason: "no telemetry target" } }, "run-1"), null);
  assert.equal(
    verificationSection({ preview: { kind: "skipped", reason: "x" }, telemetry: { kind: "disabled", reason: "y" } }, "run-1"),
    null,
  );

  // But a FAILURE is a result and must appear.
  const failed = verificationSection({ preview: { kind: "failed", reason: "teploy build failed: npm ERR!" } }, "run-1");
  assert.ok(failed !== null);
  assert.match(failed!, /FAILED/);
});

test("either half alone still produces a section", () => {
  assert.match(verificationSection({ preview: DEPLOYED }, "r")!, /Preview:/);
  assert.match(verificationSection({ telemetry: COMPARED }, "r")!, /Telemetry/);
});

test("re-running a branch leaves ONE section, not three", () => {
  const original = "Fixed the login 500.\n\n---\nTask: fix login\nRun: run-1\nGenerated by Teploy Ship.";
  const first = spliceVerification(original, verificationSection({ preview: DEPLOYED }, "run-1")!);

  const second = spliceVerification(first, verificationSection({ preview: DEPLOYED, telemetry: COMPARED }, "run-2")!);
  const third = spliceVerification(second, verificationSection({ preview: DEPLOYED, telemetry: COMPARED }, "run-3")!);

  assert.equal(third.split(VERIFICATION_START).length - 1, 1, "a branch pushed to three times must not accumulate sections");
  assert.equal(third.split(VERIFICATION_END).length - 1, 1);
  // Scope the staleness check to the SECTION: the body's own "Run: run-1" line
  // is the pull request's provenance and must survive.
  const inside = third.slice(third.indexOf(VERIFICATION_START), third.indexOf(VERIFICATION_END));
  assert.match(inside, /run-3/);
  assert.doesNotMatch(inside, /run-1|run-2/, "the stale section is replaced, not left above the new one");
  assert.match(third, /Run: run-1/, "the PR's own provenance line is not a verification artifact");

  // Everything the reviewer might have written outside the markers survives.
  assert.match(third, /Fixed the login 500\./);
  assert.match(third, /Generated by Teploy Ship\./);
});

test("a reviewer's own edits around the section are preserved", () => {
  const withNotes = spliceVerification(
    "Original body.",
    verificationSection({ preview: DEPLOYED }, "run-1")!,
  );
  const edited = `${withNotes}\n\nReviewer: please also check the retry path.`;
  const updated = spliceVerification(edited, verificationSection({ telemetry: COMPARED }, "run-2")!);

  assert.match(updated, /Original body\./);
  assert.match(updated, /Reviewer: please also check the retry path\./);
  assert.match(updated, /Telemetry/);
  assert.doesNotMatch(updated, /Preview:/, "run-2 deployed nothing, so the stale URL must go");
});

test("an empty body becomes just the section", () => {
  const section = verificationSection({ preview: DEPLOYED }, "r")!;
  assert.equal(spliceVerification("", section), section);
  assert.equal(spliceVerification("   \n\n", section), section);
});

test("a body with a start marker but no end is appended to, never cut at a guess", () => {
  const truncated = `Body text.\n${VERIFICATION_START}\n## Verification\n(cut off`;
  const updated = spliceVerification(truncated, verificationSection({ preview: DEPLOYED }, "r")!);
  assert.match(updated, /Body text\./);
  assert.match(updated, /\(cut off/, "content below a broken marker is not deleted");
  assert.match(updated, /https:\/\/preview-fix\.example\.com/);
});

test("a root suite over a change confined to one subtree gets a scope warning, and a scoped command does not", () => {
  const passed = { kind: "passed" as const, command: "go test ./...", durationMs: 12_000 };
  const warned = verificationSection({ tests: passed, changedPaths: ["nucleus/src/a.rs", "nucleus/Cargo.toml"] }, "run-1");
  assert.ok(warned !== null && warned.includes("**Scope:**") && warned.includes("`nucleus/`"), warned ?? "null");
  const scoped = verificationSection(
    { tests: { ...passed, command: "cd nucleus && cargo test --lib -q" }, changedPaths: ["nucleus/src/a.rs"] },
    "run-1",
  );
  assert.ok(scoped !== null && !scoped.includes("**Scope:**"), scoped ?? "null");
  const unknown = verificationSection({ tests: passed }, "run-1");
  assert.ok(unknown !== null && !unknown.includes("**Scope:**"), "no change list, no claim");
});

test("the proof pictures are embedded inline, named, in the order they were attached", () => {
  const section = verificationSection(
    { preview: DEPLOYED, proof: [{ name: "preview", url: "http://f/p.png" }, { name: "01-settings.png", url: "http://f/1.png" }] },
    "run-9",
  )!;
  assert.match(section, /\*\*Proof\*\*/);
  assert.match(section, /preview\n\n!\[preview\]\(http:\/\/f\/p\.png\)/);
  assert.ok(section.indexOf("p.png") < section.indexOf("1.png"), "reading order is attachment order");
  assert.equal(verificationSection({ proof: [] }, "run-9"), null, "an empty proof list says nothing");
});
